// <auto-generated />
using COREMyCookBookAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace COREMyCookBookAPI.Migrations
{
    [DbContext(typeof(MyCookBookContext))]
    [Migration("20180803203841_AddEntity")]
    partial class AddEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("COREMyCookBookAPI.Models.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Entitys");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");
                });

            modelBuilder.Entity("COREMyCookBookAPI.Models.Recipe", b =>
                {
                    b.HasBaseType("COREMyCookBookAPI.Models.Entity");

                    b.Property<string>("Cuisine");

                    b.Property<string>("Difficulty");

                    b.Property<string>("Ingredients");

                    b.Property<string>("Preparation");

                    b.Property<double>("PreparationTime");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.ToTable("Recipe");

                    b.HasDiscriminator().HasValue("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
